/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/benchmarks/gsm8k/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Benchmark */
        post: operations["start_benchmark_api_v1_benchmarks_gsm8k_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Benchmark */
        get: operations["latest_benchmark_api_v1_benchmarks_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Benchmark Run */
        get: operations["benchmark_run_api_v1_benchmarks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmarks/runs/{run_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Benchmark Records */
        get: operations["benchmark_records_api_v1_benchmarks_runs__run_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_v1_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Eligibility */
        post: operations["eligibility_api_v1_eligibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Prompt
         * @description Select exactly one pinned model using the explicit CP2 rule policy.
         */
        post: operations["route_prompt_api_v1_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing Dashboard */
        get: operations["routing_dashboard_api_v1_routing_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BenchmarkManifest */
        BenchmarkManifest: {
            /**
             * Completed Cells
             * @default 0
             */
            completed_cells: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Dataset */
            dataset: string;
            /** Dataset Revision */
            dataset_revision: string;
            /** Error Message */
            error_message?: string | null;
            /**
             * Failed Cells
             * @default 0
             */
            failed_cells: number;
            /** Generation Config */
            generation_config: {
                [key: string]: unknown;
            };
            /** Generation Config Hash */
            generation_config_hash: string;
            /** Git Commit */
            git_commit: string | null;
            mode: components["schemas"]["BenchmarkMode"];
            /** Model Ids */
            model_ids: string[];
            /** Registry Models Sha256 */
            registry_models_sha256: string;
            /** Registry Snapshot Id */
            registry_snapshot_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            status: components["schemas"]["BenchmarkStatus"];
            /**
             * Successful Cells
             * @default 0
             */
            successful_cells: number;
            /** Total Cells */
            total_cells: number;
            /**
             * Updated At Utc
             * Format: date-time
             */
            updated_at_utc: string;
        };
        /**
         * BenchmarkMode
         * @enum {string}
         */
        BenchmarkMode: "pilot" | "full";
        /** BenchmarkRecord */
        BenchmarkRecord: {
            /** Configuration */
            configuration: string;
            /** Dataset */
            dataset: string;
            /** Exact Match */
            exact_match: number;
            /** Expected Answer */
            expected_answer: string;
            /** Extracted Answer */
            extracted_answer: string | null;
            /** Extraction Method */
            extraction_method: string | null;
            /** Generation Config Hash */
            generation_config_hash: string;
            mode: components["schemas"]["BenchmarkMode"];
            /** Model Snapshot Id */
            model_snapshot_id: string;
            /** Prompt Template Version */
            prompt_template_version: string;
            /** Rendered Prompt */
            rendered_prompt: string;
            result: components["schemas"]["GenerationResult"];
            /** Revision */
            revision: string;
            /** Run Id */
            run_id: string;
            /** Sample Id */
            sample_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Source Index */
            source_index: number;
            /** Split */
            split: string;
        };
        /** BenchmarkRunView */
        BenchmarkRunView: {
            manifest: components["schemas"]["BenchmarkManifest"];
            summary?: components["schemas"]["BenchmarkSummary"] | null;
        };
        /** BenchmarkStartRequest */
        BenchmarkStartRequest: {
            /** @default full */
            mode: components["schemas"]["BenchmarkMode"];
        };
        /**
         * BenchmarkStatus
         * @enum {string}
         */
        BenchmarkStatus: "pending" | "running" | "budget_paused" | "interrupted" | "completed" | "completed_with_errors" | "failed";
        /** BenchmarkSummary */
        BenchmarkSummary: {
            /**
             * Generated At Utc
             * Format: date-time
             */
            generated_at_utc: string;
            /** Models */
            models: components["schemas"]["ModelBenchmarkSummary"][];
            /** Run Id */
            run_id: string;
        };
        /** CapabilitySpec */
        CapabilitySpec: {
            /**
             * Structured Output
             * @default false
             */
            structured_output: boolean;
            /**
             * Tools
             * @default false
             */
            tools: boolean;
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** Prompt */
            prompt: string;
            /**
             * Save
             * @default false
             */
            save: boolean;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /**
             * Comparison Id
             * Format: uuid
             */
            comparison_id?: string;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc?: string;
            /** Prompt */
            prompt: string;
            /** Results */
            results: components["schemas"]["GenerationResult"][];
            /** Saved */
            saved: boolean;
        };
        /**
         * CostSource
         * @enum {string}
         */
        CostSource: "provider" | "registry_calculation" | "unavailable";
        /** EligibilityRequest */
        EligibilityRequest: {
            /**
             * Min Context Tokens
             * @default 500000
             */
            min_context_tokens: number;
        };
        /** EligibilityResponse */
        EligibilityResponse: {
            /** Results */
            results: components["schemas"]["EligibilityResult"][];
        };
        /** EligibilityResult */
        EligibilityResult: {
            /** Eligible */
            eligible: boolean;
            evaluated_requirements: components["schemas"]["EligibilityRequest"];
            /** Model Id */
            model_id: string;
            /** Model Snapshot Id */
            model_snapshot_id: string;
            /** Reasons */
            reasons: string[];
        };
        /** GenerationResult */
        GenerationResult: {
            /** Attempt Number */
            attempt_number: number;
            /**
             * Completed At Utc
             * Format: date-time
             */
            completed_at_utc: string;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** @default unavailable */
            cost_source: components["schemas"]["CostSource"];
            /** Cost Usd */
            cost_usd?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /**
             * Provider
             * @default openrouter
             */
            provider: string;
            /** Provider Request Id */
            provider_request_id?: string | null;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Requested Model Id */
            requested_model_id: string;
            /** Served Model Id */
            served_model_id?: string | null;
            /**
             * Started At Utc
             * Format: date-time
             */
            started_at_utc: string;
            status: components["schemas"]["GenerationStatus"];
            /** Text */
            text?: string | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /**
         * GenerationStatus
         * @enum {string}
         */
        GenerationStatus: "success" | "provider_error" | "timeout" | "rate_limited" | "invalid_response" | "model_mismatch";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Active Benchmark Run Id */
            active_benchmark_run_id: string | null;
            /** Credential Configured */
            credential_configured: boolean;
            /** Registry Loaded */
            registry_loaded: boolean;
            /** Registry Snapshot Id */
            registry_snapshot_id: string | null;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ModelBenchmarkSummary */
        ModelBenchmarkSummary: {
            /** Accuracy */
            accuracy: number;
            /** Attempted */
            attempted: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Correct */
            correct: number;
            /** Error Counts */
            error_counts: {
                [key: string]: number;
            };
            /** Failed */
            failed: number;
            /** Mean Latency Ms */
            mean_latency_ms: number | null;
            /** Median Latency Ms */
            median_latency_ms: number | null;
            /** Model Id */
            model_id: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Successful */
            successful: number;
            /** Total Cost Usd */
            total_cost_usd: string | null;
            /** Total Tokens */
            total_tokens: number;
        };
        /** ModelSpec */
        ModelSpec: {
            capabilities: components["schemas"]["CapabilitySpec"];
            /** Context Length */
            context_length: number;
            /** Display Name */
            display_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Input Modalities */
            input_modalities: string[];
            /**
             * Metadata As Of
             * Format: date-time
             */
            metadata_as_of: string;
            /** Output Modalities */
            output_modalities: string[];
            pricing: components["schemas"]["PricingSpec"];
            /** Provider */
            provider: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Url */
            source_url: string;
            /** Supported Parameters */
            supported_parameters: string[];
        };
        /** PaginatedRecords */
        PaginatedRecords: {
            /** Items */
            items: components["schemas"]["BenchmarkRecord"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PricingSpec */
        PricingSpec: {
            /** Completion Per Token */
            completion_per_token?: string | null;
            /** Prompt Per Token */
            prompt_per_token?: string | null;
        };
        /** RegistrySnapshot */
        RegistrySnapshot: {
            /**
             * Metadata As Of
             * Format: date-time
             */
            metadata_as_of: string;
            /** Models */
            models: components["schemas"]["ModelSpec"][];
            /** Models Sha256 */
            models_sha256: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Url */
            source_url: string;
        };
        /** RouteRequest */
        RouteRequest: {
            /**
             * Min Context Tokens
             * @default 1
             */
            min_context_tokens: number;
            /** @default balanced */
            priority: components["schemas"]["RoutingPriority"];
            /** Prompt */
            prompt: string;
        };
        /** RouteResponse */
        RouteResponse: {
            decision: components["schemas"]["RoutingDecision"];
            result: components["schemas"]["GenerationResult"];
        };
        /** RoutingDashboard */
        RoutingDashboard: {
            /** Note */
            note: string;
            /** Source Cells */
            source_cells: number;
            /** Source Dataset */
            source_dataset: string;
            /** Source Run Id */
            source_run_id: string;
            /** Strategies */
            strategies: components["schemas"]["RoutingStrategySummary"][];
        };
        /** RoutingDecision */
        RoutingDecision: {
            /** Eligible Model Ids */
            eligible_model_ids: string[];
            priority: components["schemas"]["RoutingPriority"];
            /** Reason */
            reason: string;
            /** Selected Model Id */
            selected_model_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Task Signals */
            task_signals: string[];
        };
        /**
         * RoutingPriority
         * @enum {string}
         */
        RoutingPriority: "cost" | "quality" | "latency" | "balanced";
        /** RoutingStrategySummary */
        RoutingStrategySummary: {
            /** Accuracy */
            accuracy: number;
            /** Accuracy When Served */
            accuracy_when_served: number | null;
            /** Attempted */
            attempted: number;
            /** Correct */
            correct: number;
            /** Failed */
            failed: number;
            /** Label */
            label: string;
            /** Mean Latency Ms */
            mean_latency_ms: number | null;
            /** Selected Model Counts */
            selected_model_counts: {
                [key: string]: number;
            };
            /** Strategy Id */
            strategy_id: string;
            /** Successful */
            successful: number;
            /** Total Cost Usd */
            total_cost_usd: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_benchmark_api_v1_benchmarks_gsm8k_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_benchmark_api_v1_benchmarks_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunView"];
                };
            };
        };
    };
    benchmark_run_api_v1_benchmarks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    benchmark_records_api_v1_benchmarks_runs__run_id__records_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecords"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eligibility_api_v1_eligibility_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrySnapshot"];
                };
            };
        };
    };
    route_prompt_api_v1_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routing_dashboard_api_v1_routing_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingDashboard"];
                };
            };
        };
    };
}
